version: "3.9"

services:
  web:
    container_name: incameo-web
    command: >
      sh -c "
      npm run dev"
    build: 
      context: .
      dockerfile: .docker/web/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web-service:/incameo/vue-web
      - node_modules:/incameo/vue-web/app/node_modules/
    working_dir: /incameo/vue-web/app
    depends_on:
      - api

  api:
    container_name: incameo-api
    command: >
      sh -c "
      python app/manage.py migrate &&
      python app/manage.py runserver 0.0.0.0:8000"
    build: 
      context: .
      dockerfile: .docker/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api-service:/incameo/django-api
      - venv:/incameo/django-api/venv
    working_dir: /incameo/django-api
    env_file:
      - .env
    # depends_on:
    #   - db

  # db:
  #   container_name: incameo-db
  #   image: postgres:14-alpine
  #   environment:
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #   volumes:
  #     - postgresdb:/var/lib/postgresql/data
  #   env_file:
  #     - .env

volumes:
  # postgresdb:
  node_modules:
  venv: