version: "3.9"

services:
  web:
    container_name: incameo-web
    command: >
      sh -c "
      npm run dev"
    build: 
      context: .
      dockerfile: .docker/web/Dockerfile
    image: incameo-web:dev
    ports:
      - "3000:3000"
    volumes:
      - ./web-service:/incameo/vue-web
    depends_on:
      - api

  api:
    container_name: incameo-api
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    build: 
      context: .
      dockerfile: .docker/api/Dockerfile
    image: incameo-api:dev
    ports:
      - "8000:8000"
    volumes:
      - ./api-service:/incameo/django-api
    env_file:
      - .env
