# Generated by Django 3.1.6 on 2021-03-14 06:50

import api.auth.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_fullname', models.CharField(max_length=50, verbose_name='full name')),
                ('user_username', models.CharField(max_length=15, unique=True, validators=[api.auth.validators.AlphanumericUsernameValidator], verbose_name='username')),
                ('user_email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('user_dob', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user is verified. Unselect this if user not verified.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether this user should be treated as staff. Staff users can login to Admin', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
