version: "3.9"

services:
  web:
    container_name: incameo-web
    build: 
      context: .
      dockerfile: .docker/web/Dockerfile
    image: incameo-web:dev
    ports:
      - "3000:3000"
    volumes:
      - "./web-service/app:/incameo/nuxt-web/app"
      - node_modules:/incameo/nuxt-web/app/node_modules
    env_file:
      - .env
    depends_on:
      - api

  api:
    container_name: incameo-api
    build: 
      context: .
      dockerfile: .docker/api/Dockerfile
    image: incameo-api:dev
    ports:
      - "8000:8000"
    volumes:
      - ./api-service/app:/incameo/django-api/app
    env_file:
      - .env

volumes:
  node_modules:
